具体时间:[2020-02-22 02:32:21,584][default:INFO(155)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第155行]-登录成功

具体时间:[2020-02-22 10:15:28,819][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 10:15:29,102][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 10:15:36,424][default:INFO(155)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第155行]-登录成功

具体时间:[2020-02-22 10:32:18,779][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 10:32:25,615][default:INFO(155)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第155行]-登录成功

具体时间:[2020-02-22 10:59:31,690][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 10:59:40,641][default:INFO(155)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第155行]-登录成功

具体时间:[2020-02-22 20:17:43,676][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 20:17:43,870][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 20:17:53,222][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 20:18:04,884][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 20:19:31,409][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 20:19:41,228][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 20:25:09,970][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 20:25:16,251][default:INFO(157)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第157行]-登录成功

具体时间:[2020-02-22 20:34:13,515][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 20:34:13,686][default:INFO(22)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\user\login_required.py]模块名:[login_required:]函数名:[process_request]:
[第22行]-用户没有登录, 跳转到登录页面

具体时间:[2020-02-22 20:34:21,731][default:INFO(155)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py]模块名:[views:]函数名:[account_login]:
[第155行]-登录成功

具体时间:[2020-02-23 00:45:15,314][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
具体时间:[2020-02-23 00:45:16,955][default:ERROR(244)]
当前文件位置:[D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py]模块名:[Utils:]函数名:[wrapper]:
[第244行]-[Error in Lib.Utils] msg: 'approve' is not a registered namespace
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 59, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 74, in reverse
    extra, resolver = resolver.namespace_dict[ns]
KeyError: 'approve'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\Lib\Utils.py", line 240, in wrapper
    func(*args, **kwargs)
  File "D:\Program Files\Python36\lib\site-packages\django\views\decorators\http.py", line 40, in inner
    return func(request, *args, **kwargs)
  File "D:\WorkData\VSCodeProjects\TY_RMS_BZP_Manage\TY_RMS_Multiple_Manage\views.py", line 63, in home
    return render(request, 'home.html', locals())
  File "D:\Program Files\Python36\lib\site-packages\django\shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Program Files\Python36\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Program Files\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 943, in render
    bit = node.render_annotated(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\base.py", line 910, in render_annotated
    return self.render(context)
  File "D:\Program Files\Python36\lib\site-packages\django\template\defaulttags.py", line 447, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Program Files\Python36\lib\site-packages\django\urls\base.py", line 84, in reverse
    raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: 'approve' is not a registered namespace
